apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-service
  labels:
    app: main-app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-app-service
  template:
    metadata:
      labels:
        app: main-app-service
    spec:
      containers:
        - name: main-app-service
          image: uvinitharindi/main-service:v4
          imagePullPolicy: Always
          ports: 
            - containerPort: 3003