apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-service
  labels:
    app: pull-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pull-service
  template:
    metadata:
      labels:
        app: pull-service
    spec:
      containers:
        - name: pull-service
          image: uvinitharindi/pulls-service:v42
          imagePullPolicy: Always
          ports:
            - containerPort: 3002