apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulls-service
  labels:
    app: pulls-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulls-service
  template:
    metadata:
      labels:
        app: pulls-service
    spec:
      containers:
        - name: pulls-service
          image: uvinitharindi/pulls-service:latest 
          imagePullPolicy: Always
          ports: 80
            - containerPort: 3002